import{a as d,S,i as v}from"./assets/vendor-951421c8.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function p(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=p(t);fetch(t.href,r)}})();const w="https://pixabay.com/api/",q="42034785-c436f003c310c5b5229f24b7b";d.defaults.baseURL=w;let m;const o={key:q,q:"",image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:20,page:1},P=new S(".gallery a",{overlayOpacity:.7,captionsData:"alt",captionDelay:500,captionPosition:"center"}),y=document.querySelector(".gallery-form"),f=document.querySelector(".search-input"),h=document.querySelector(".gallery"),i=document.querySelector(".loader"),c=document.querySelector(".load-more-btn");async function F(e){if(e.preventDefault(),!f.value.trim()){u("Please fill in the search field");return}try{h.innerHTML="",a(i,!0),a(c,!1),o.q=f.value.trim(),o.page=1;const s=await g();m=s.totalHits,b(s)}catch(s){console.log(s)}}async function C(){try{a(i,!0),a(c,!1);const e=await g();b(e)}catch(e){console.log(e)}}async function g(){return(await d.get("",{params:o})).data}function b(e){if(!e.total){u("Sorry, there are no images matching your search query. Please, try again!"),a(i,!1);return}const s=e.hits.map(({largeImageURL:p,webformatURL:l,tags:t,likes:r,views:n,comments:L,downloads:E})=>`<li class="gallery-item">
          <a href="${p}">
            <img class="api-img" src="${l}" alt="${t}">
            <div class="img-desc">
            <p class="para">Likes: <span class="span"> <br/>${r}</span></p>
            <p class="para">Views: <span class="span"> <br/>${n}</span></p>
            <p class="para">Comments: <span class="span"> <br/>${L}</span></p>
            <p class="para">Downloads: <span class="span"> <br/>${E}</span></p>
            </div>
          </a>
        </li>`).join("");h.insertAdjacentHTML("beforeend",s),a(i,!1),k(),M(),P.refresh(),y.reset()}function k(){Math.ceil(m/o.per_page)===o.page?u("We're sorry, but you've reached the end of search results."):(o.page+=1,a(c,!0))}function a(e,s){s?e.classList.remove("hidden"):e.classList.add("hidden")}function M(){if(o.page>1){const e=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e.height*2,left:0,behavior:"smooth"})}}function u(e){v.show({position:"bottomCenter",title:"X",titleColor:"#FFF5E0",titleSize:"20px",message:e,backgroundColor:"#FF6969",messageColor:"#FFF5E0",messageSize:"14px",close:!1,closeOnClick:!0,closeOnEscape:!0})}y.addEventListener("submit",e=>F(e));c.addEventListener("click",()=>C());
//# sourceMappingURL=commonHelpers.js.map
